### ISSUE TITLE
More flexibility with tags

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/aws-ecr-client-golang#13]
The issue I faced with aws-ecr-client is that the [docker/metadata-action](https://github.com/docker/metadata-action) outputs tags in the same format as the the tags input of [docker/build-push-action](https://github.com/docker/build-push-action) expect. Whereas aws-ecr-client only wants the tag (part after :). It's cumbersome to get it into AWS_ECR_CLIENT_IMAGE_TAG and AWS_ECR_CLIENT_ADDITIONAL_TAGS in the right format. There is [a join function](https://docs.github.com/en/actions/learn-github-actions/expressions#join) but then I still need some way to split on : on each value

**Comment by legal90** [comment]
@Andrey9kin I suggest the following solution:

1) Stick to the same grammar both in docs and in the code. From the canonical OCI image reference spec (defined in [distribution/distribution](https://github.com/distribution/distribution/blob/26163d82560f4dda94bd7b87d587f94644c5af79/reference/reference.go#L4-L26):
-  **image reference** is what you probably meant as the "right format" here, e.q. a full ref like `fictional.registry.example:10443/folder/name:tag`
- **image name** is the part of the image ref _before_ the last colon symbol, e.q. `fictional.registry.example:10443/folder/name` from the example above
- **image tag** is the part of the image ref _after_ the last colon symbol, e.q. `tag` from the example above

2) Replace arguments `--destination-repo`, `--additional-tags`, `--tag` with a single argument `--images` which will have a comma- or space-separated list of all image references we want to push after a successful verification.
As I understand, we can support any OCI-compatible registries here, not only AWS ECR repos.

3) Make the argument `--stage-repo` mandatory and maybe rename it to `--stage-ecs-repo` , expecting that to be an ECR repo. We will still generate the image tag automatically.

**Comment by Andrey9kin** [comment]
@legal90  sorry for the delay

1. yes
2. yes, yeah we could support not only ECR but then you would need to have auth logic for other registries. I would rather stick to UNIX philosophy. Do one thing and do it well
3. why would we need to have stage-repo arg mandatory? i could imagine people wanting to keep things in the same repo so do not want to force a certain way of working on them unless you have a good reason.

**Comment by legal90** [comment]
@Andrey9kin 
2. I didn't mean to add any new feature to support that. It's just how I see it might be used after the implementing of my proposal. The arg `--images` is gonna be generic and users can pass any OCI-compatible image refs there . There could be different repos and `Push` function will still work fine (as long as auth/docker login is already done) https://github.com/fivexl/aws-ecr-client-golang/blob/53a49f863bdf62afc81d744b83ac70785ded4b01/commands.go#L21
That doesn't violate UNIX philosophy.

3. That's because of the definition of `--images` arg I explained above. Since there could be a list of images, we don't know which one should be used as a `--stage-repo` value. That's why it will have to be passed explicitly.

**Comment by Andrey9kin** [comment]
2. Yes. understood your idea regarding --images and liked it. My comment regarding UNIX philosophy was about supporting other registries other than ECR.
3. Can we say that if --stage-repo is not provided then the registry of the first image will be used as a staging repo? This is how it would typically work if you do not specify --stage-repo and specify only one image

**Comment by legal90** [comment]
> Can we say that if --stage-repo is not provided then the registry of the first image will be used as a staging repo? This is how it would typically work if you do not specify --stage-repo and specify only one image

OK, yes, I can implement it that way 👍

**Comment by Andrey9kin** [comment]
@legal90 and if you want to rename it to --stage-ecr-repo or --stage-ecr-registry feel free to do that. Anyway, we are changing the API
