### ISSUE TITLE
Replace build.sh with https://github.com/mitchellh/gox

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/aws-ecr-client-golang#5]

**Comment by legal90** [comment]
What do you think about trying https://goreleaser.com/ instead ?  I use it in this project: https://github.com/legal90/awscurl

**Comment by Andrey9kin** [comment]
@legal90 Yes, goreleaser seems to be the default way to do releases nowadays. Also, used it in one of the projects and liked it
